####################################################
# Students' Makefile for the CS:APP Architecture Lab
####################################################

sim:
	(cd sim; make)

# Use this rule to "hand in" Part A ("make handin-parta")
handin-parta:
	git add sim/misc/sum.ys
	git add sim/misc/rsum.ys
	git add sim/misc/copy.ys
	git commit -m "handin part a"
	git push

clean:
	rm -f *~ *.o
